supportportal/apps/companies/urls.py
from django.conf.urls import patterns, url
from apps.companies import views

urlpatterns = patterns('',
    # Views
    url(r'^(?P<company_id>\d+)/$', views.detail, name='detail'),
    url(r'^$', views.index, name='index'),
    # AJAX
    url(r'^index/$', views.get_companies, name='getcompanies'),
    url(r'^detail/(?P<company_id>\d+)/$', views.get, name='get'),
    url(r'^set/(?P<company_id>\d+)/$', views.set, name='set'),
    url(r'^services/$', views.get_services, name='getservices'),
    url(r'^feeds/(?P<company_id>\d+)/$', views.get_feeds, name='getfeeds'),
    url(r'^contacts/(?P<company_id>\d+)/$', views.get_contacts, name='getcontacts'),
)

supportportal/appsdir/companies/urls.py
from django.conf.urls import patterns, url
from appsdir.companies import views


urlpatterns = patterns('',
    url(r'^(?P<company_id>\d+)/$', views.detail, name='detail'),
    url(r'^$', views.index, name='index'),
)

supportportal/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from api import router

urlpatterns = patterns('',
    url('^activity/', include('actstream.urls')),
    url('^dashboard/', include('appsdir.dashboard.urls', namespace='dashboard')),
    url('^search/', include('appsdir.search.urls', namespace='search')),
    url('^support/', include('appsdir.support.urls', namespace='tickets')),
    url('^knowledgebase/', include('appsdir.knowledgebase.urls', namespace='knowledgebase')),
    url('^login/', 'django.contrib.auth.views.login', {'template_name': 'registration/login.html'}, name='login'),
    url('^logout/', 'django.contrib.auth.views.logout', {'next_page': '/login/'}),
    url('^accounts/contact/', include('appsdir.contacts.urls', namespace='contacts')),
    url('^accounts/company/', include('appsdir.companies.urls', namespace='companies')),
    url('^reports/', include('appsdir.reports.urls', namespace='reports')),
    url('^groups/', include('appsdir.groups.urls', namespace='groups')),
    url('^announcements/', include('appsdir.announcements.urls', namespace='announcements')),
    url('^api/', include(router.urls)),
    url('^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url('^$', 'django.contrib.auth.views.login', {'template_name': 'registration/login.html'}, name='login'),
)

if settings.DEBUG:
    urlpatterns += patterns('', ('^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

supportportal/appsdir/companies/models.py
import random, string
from django.db import models
from django.conf import settings
from simple_history.models import HistoricalRecords


UID_LENGTH = 8

class Company(models.Model):
    name = models.CharField(max_length=32, unique=True, db_index=True)
    uid = models.CharField(max_length=UID_LENGTH, null=True, unique=True, editable=False)
    description = models.TextField(blank=True, null=True)
    website = models.URLField(blank=True, null=True)
    address1 = models.CharField(max_length=64, blank=True, null=True)
    address2 = models.CharField(max_length=64, blank=True, null=True)
    city = models.CharField(max_length=32, blank=True, null=True)
    state = models.CharField(max_length=16, blank=True, null=True)
    zip = models.CharField(max_length=16, blank=True, null=True)
    phone = models.CharField(max_length=16, blank=True, null=True)
    fax = models.CharField(max_length=16, blank=True, null=True)
    status = models.BooleanField(default=True, blank=True)
    history = HistoricalRecords()
    changed_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, related_name="%(app_label)s_%(class)s_changed_by")
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        # Generate UID on create
        if not self.uid:
            while True:
                hash = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(UID_LENGTH))
                if not Company.objects.filter(uid=hash):
                    self.uid = hash
                    break

        super(Company, self).save(*args, **kwargs)

    def __unicode__(self):
        return '%s' % (self.name)

    def get_absolute_url(self):
        return "/accounts/company/%i/" % self.id

    @property
    def _history_user(self):
        return self.changed_by

supportportal/apps/companies/forms.py
from django.forms import ModelForm
from .models import Company

class CompanyForm(ModelForm):
	class Meta:
		model = Company
		fields = ['name', 'description', 'address1', 'address2', 'city', 'state', 'zip', 'website', 'phone', 'fax']

supportportal/appsdir/companies/forms.py
from django.forms import ModelForm
from .models import Company


class CompanyForm(ModelForm):
	class Meta:
		model = Company
		fields = ['name', 'description', 'address1', 'address2', 'city', 'state', 'zip', 'website', 'phone', 'fax']

supportportal/apps/companies/views.py
# System
import logging
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
# Project
from apps.contacts.models import Contact
from apps.contacts.forms import ContactCreationForm
from apps.loggers.models import ActionLogger
from common.decorators import validated_request, validated_staff
from common.helpers import format_ajax_response
# App
from .models import Company
from .forms import CompanyForm


logger = logging.getLogger(__name__)


@login_required
def detail(request, company_id):
    """Company Detail View

        Retrieve Company details as specified by company.pk.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        @login_required
            request.user.is_authenticated() must be True
    Parameters
        request: HttpRequest
        company_id: int company id
    Returns
        HttpResponse (companies/detail.html)
            company_detail: queryset Company of specified company_id
            company_form: form CompanyForm
            contact_form: form ContactCreationForm
    """
    company = get_object_or_404(Company, pk=company_id)

    company_form = CompanyForm(instance=company)
    contact_form = ContactCreationForm()

    return render(request, 'companies/detail.html', {
        'company_detail': company,
        'company_form': company_form,
        'contact_form': contact_form
    })


@validated_staff
def index(request):
    """Company Index View

        Retrieves listing of Companies.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        @validated_staff
            request.user.is_staff() must be True
    Parameters
        request: HttpRequest
    Returns
        HttpResponse (companies/index.html)
            companyform: form CompanyForm
    """
    return render(request, 'companies/index.html', {'companyform':  CompanyForm()})


@validated_staff
@validated_request(None)
def get_companies(request):
    """Get Companies

        Retrieves listing of Companies.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        @validated_staff
            request.user.is_staff() must be True
        @validated_request
            request.method must be POST
            request.is_ajax() must be True
            request.user.is_authenticated() must be True
    Parameters
        request: HttpRequest
    Returns
        HttpResponse (JSON)
            success: int status result
            message: str response message
            *data:
                companies:
                    name: str company name
                    status: bool company status
                    id: int company id
    """
    try:
        companies = []
        for company in Company.objects.all():
            companies.append(company.dump_to_dict())

        return format_ajax_response(True, "Companies list retrieved successfully.", {'companies': companies})
    except Exception as ex:
        logging.error("failed to get_companies: %s" % ex)
        return format_ajax_response(False, "There was a problem retrieving the companies listing.")


@validated_staff
@validated_request(None)
def get_services(request):
    """Get Companies

        Retrieves listing of Companies.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        @validated_staff
            request.user.is_staff() must be True
        @validated_request
            request.method must be POST
            request.is_ajax() must be True
            request.user.is_authenticated() must be True
    Parameters
        request: HttpRequest
    Returns
        HttpResponse (JSON)
            success: int status result
            message: str response message
            *data:
                companies:
                    name: str company name
                    status: bool company status
                    id: int company id
    """
    try:
        company = Company.objects.get(pk=int(request.POST['company_id']))

        services = []
        for service in company.services.all():
            services.append({'name': service.name, 'id': service.pk})

        return format_ajax_response(True, "Company's services retrieved successfully.", {'services': services})
    except Exception as ex:
        logging.error("failed to get_services: %s" % ex)
        return format_ajax_response(False, "There was a problem retrieving the company's services.")


@validated_request(None)
def get(request, company_id):
    """Get Company Details

        Retrieve Company details as specified by company.pk.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        @validated_request
            request.method must be POST
            request.is_ajax() must be True
            request.user.is_authenticated() must be True
    Parameters
        request: HttpRequest
        company_id: int company id
    Returns
        HttpResponse (JSON)
            success: int status result
            message: str response message
            *data:
                company:
                    name:
                    description:
                    created:
                    modified:
                    website:
                    address1:
                    address2:
                    city:
                    state:
                    zip:
                    phone:
                    fax:
    """
    try:
        company = Company.objects.get(pk=company_id)

        if not (request.user.company_id == int(company_id) or request.user.is_admin == True):
            raise Exception("Fobiden: requesting user doesn't have permission to specified Company.")

        return format_ajax_response(True, "Company profile retrieved successfully.", {'company': company.dump_to_dict(True)})
    except Exception as ex:
        logger.error("Failed to get: %s" % ex)
        return format_ajax_response(False, "There was a problem retrieving the company profile.")


@validated_request(None)
def set(request, company_id):
    """Set Company

        Creates Company, or updates existing Company as specified by company.pk.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        @validated_request
            request.method must be POST
            request.is_ajax() must be True
            request.user.is_authenticated() must be True
    Parameters
        request: HttpRequest
            name:
            description:
            address1:
            address2:
            city:
            state:
            zip:
            website:
            phone:
            fax:
        company_id: int company id
    Returns
        HttpResponse (JSON)
            success: int status result
            message: str response message
    """
    try:
        if not (request.user.company_id == int(company_id) or request.user.is_admin == True):
            raise Exception("Fobiden: requesting user doesn't have permission to specified Company.")

        if request.user.is_staff and not int(company_id):
            form = CompanyForm(request.POST)
            if form.is_valid():
                company = form.save()
                ActionLogger().log(request.user, "created", "Company %s" % company)
                return format_ajax_response(True, "Company created successfully.")
            else:
                return format_ajax_response(False, "Form data failed validation.", errors=dict((k, [unicode(x) for x in v]) for k,v in form.errors.items()))
        else:
            company = Company.objects.get(pk=company_id)

            form = CompanyForm(request.POST, instance=company)
            if form.is_valid():
                form.save()
                ActionLogger().log(request.user, "modified", "Company %s" % company)
                return format_ajax_response(True, "Company profile updated successfully.")
            else:
                return format_ajax_response(False, "Form data failed validation.", errors=dict((k, [unicode(x) for x in v]) for k,v in form.errors.items()))
    except Exception as ex:
        logger.error("Failed to set: %s" % ex)
        return format_ajax_response(False, "There was an error setting the Company record.")


@validated_request(None)
def get_contacts(request, company_id):
    """Get Company Contacts

        Retrieve listing of Contacts belonging to Company as specified by company.pk.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        @validated_request
            request.method must be POST
            request.is_ajax() must be True
            request.user.is_authenticated() must be True
    Parameters
        request: HttpRequest
        company_id: int company id
    Returns
        HttpResponse (JSON)
            success: int status result
            message: str response message
            *data:
                contacts:
                    first_name:
                    last_name:
                    role:
                    id:
                    email:
    """
    try:
        company = Company.objects.get(pk=company_id)

        if not (request.user.company_id == int(company_id) or request.user.is_admin == True):
            raise Exception("Fobiden: requesting user doesn't have permission to specified Company.")

        contacts = []
        for contact in Contact.objects.filter(company=company):
            contacts.append(contact.dump_to_dict())

        return format_ajax_response(True, "Company contacts listing retrieved successfully.", {'contacts': contacts})
    except Exception as ex:
        logger.error("Failed to get_contacts: %s" % ex)
        return format_ajax_response(False, "There was a problem retrieving company contacts listing.")


@validated_request(None)
def get_feeds(request, company_id):
    """Get Company activity feeds

        Retrieve listing of actionloggers and authenticationloggers for Company as specified by company.pk.

    Middleware

supportportal/appsdir/companies/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import get_object_or_404, render
from appsdir.contacts.forms import ContactCreationForm
from .models import Company
from .forms import CompanyForm

@login_required
def detail(request, company_id):
    """Company Detail View

        Retrieve Company details as specified by company.pk.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        @login_required
            request.user.is_authenticated() must be True
    Parameters
        request: HttpRequest
        company_id: int company id
    Returns
        HttpResponse (companies/detail.html)
            company_detail: queryset Company of specified company_id
            company_form: form CompanyForm
            contact_form: form ContactCreationForm
    """
    company = get_object_or_404(Company, pk=company_id)

    data = {
        'company_id': company_id,
        'company_form': CompanyForm(instance=company),
        'contact_form': ContactCreationForm()
    }

    return render(request, 'companies/detail.html', data)

@staff_member_required
def index(request):
    """Company Index View

        Retrieves listing of Companies.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        @staff_member_required
            request.user.is_staff() must be True
    Parameters
        request: HttpRequest
    Returns
        HttpResponse (companies/index.html)
            companyform: form CompanyForm
    """
    return render(request, 'companies/index.html', {'companyform':  CompanyForm()})

supportportal/apps/companies/templates/companies/index.html
{% extends "base.html" %}

{% load staticfiles %}
{% load common_tags %}

{% block sitetitle %}| Companies{% endblock %}
{% block heading %}Administration <small>Companies</small>{% endblock %}

{% block breadcrumbs %}
    <li>Companies</a></li>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static '/assets/plugins/data-tables/DT_bootstrap.css' %}" />
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static '/assets/plugins/data-tables/jquery.dataTables.js' %}"></script>
    <script type="text/javascript" src="{% static '/assets/plugins/data-tables/DT_bootstrap.js' %}"></script>
    <script type="text/javascript">
        function getCompanies() {
            $("#companies-index-table").dataTable().fnDestroy();
            $("#companies-index-tbody").html("");

            function onSuccessCallback(result) {
                if(!jQuery.isEmptyObject(result) && result.hasOwnProperty('success') && result.hasOwnProperty('message') && result.hasOwnProperty('data')) {
                    if(result.success == 1) {
                        for(x in result.data.companies) {
                            $("#companies-index-tbody").append(' \
                                <tr data-id="'+result.data.companies[x].id+'"> \
                                    <td>'+result.data.companies[x].id+'</td> \
                                    <td>'+result.data.companies[x].name+'</td> \
                                    <td>'+result.data.companies[x].status+'</td> \
                                    <td>'+result.data.companies[x].created+'</td> \
                                    <td>'+result.data.companies[x].modified+'</td> \
                                </tr>'
                            );
                        }

                        $("#companies-index-table").dataTable({"aoColumnDefs": [],"aaSorting": [[0, 'asc']]});
                    }
                    else {
                      $("#companies-index-tbody").html("<tr class='has-error'><td colspan=4><em>"+result.message+"</em></td></tr>");
                    }
                }
            }

            $.ajax({
                url: "{%url 'companies:getcompanies' %}",
                type: "POST",
                success: onSuccessCallback,
                error: defaultErrorCallback
            });
        }

      function addCompany() {
          function onSuccessCallback(result) {
              if(!jQuery.isEmptyObject(result) && result.hasOwnProperty('success') && result.hasOwnProperty('message')) {
                  $('.modal-alert').html(result.message);
                  $('.modal-alert').fadeIn();

                  if(result.success == 1) {
                    $('.modal-alert').addClass('alert alert-success');
                    getCompanies();
                    setTimeout("$('.modal.in').modal('hide')",500);
                  }
                  else {
                      $('.modal-alert').addClass('alert alert-danger');
                      if(result.hasOwnProperty('errors')) {
                          $.each(result.errors, function(k,v) {
                              $("#id_"+k).closest('tr').addClass("has-error");
                              $("#"+k+"-help").html(v);
                          });
                      }
                  }

                  setTimeout("$('.modal-alert').fadeOut()",2000);
                  $('.modal-alert').removeClass().addClass('modal-alert');
              }
          }

          $.ajax({
              url: "{% url 'companies:set' 0 %}",
              type: "POST",
              data: $("#company-add-form").serialize(),
              success: onSuccessCallback,
              error: defaultErrorCallback
          });
      }
    </script>
{% endblock %}

{% block jquery_document_ready %}
    getCompanies();

    $('#companies-index-table').on('click', 'tr', function () {
        if($(this).data('id')) {
            window.location = "{% url 'companies:detail' 0 %}".replace('0', $(this).data('id'));
	      }
    });

  $(document)
        .on('click', 'a.refresh-companies', function (e) {
            e.preventDefault();
            getCompanies();
        })
        .on('click', 'a.show-set-company-modal', function (e) {
            e.preventDefault();
            $('#company-add-form').trigger('reset');
            $('#set-company-modal').modal('show');
        })
        .on('click', 'a.set-company-form-submit', function (e) {
            e.preventDefault();
            addCompany();
        });
{% endblock %}

{% block content %}
 <!-- BEGIN COMPANIES INDEX CONTENT -->

    <!-- BEGIN CONTENT HEAD -->
    <div class="row page-head">
        <div class="col-md-6"><h3>Companies</h3></div>
        <div class="col-md-6 text-right">
            <div class="btn-group">
                <a href="#" role="button" class="refresh-companies" alt="Refresh Companies"><i class="fa fa-refresh"></i></a>
                <a href="#" role="button" class="show-create-company-modal" data-toggle="modal" alt="Create Company"><i class="fa fa-plus"></i></a>
            </div>
        </div>
    </div>
    <!-- END CONTENT HEAD -->

    <!-- BEGIN CONTENT BODY -->
      <!-- BEING COMPANIES TABLE -->
      <table class="table table-hover" id="companies-index-table">
          <thead class="row">
              <tr>
                  <th class="col-md-1">ID</th>
                  <th class="col-md-3">Name</th>
                  <th class="col-md-2">Status</th>
                  <th class="col-md-3">Created</th>
                  <th class="col-md-3">Last Update</th>
              </tr>
          </thead>
          <tbody id="companies-index-tbody"></tbody>
      </table>
      <!-- END COMPANIES TABLE -->
    <!-- END CONTENT BODY -->

    <!-- BEGIN MODAL -->
    <div id="set-company-modal" class="modal fade in" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3>Add Company</h3>
                </div>
                <div class="modal-body">
                    <!-- BEGIN MODAL BODY -->
                    <div class="modal-alert"></div>
                      <!-- BEGIN COMPANY FORM -->
                      <form class="form form-vertical" role="form" id="company-add-form">
                        <table class="table table-hover" id="company-profile-form-table">
                          {% for field in companyform %}
                            <tr class="form-group">
                              <td><label class="control-label">{{ field.label_tag }}</label></td>
                              <td>
                                <div class="controls{% if field.errors %} error{% endif %}">
                                  {{ field|addcss:"form-control" }}
                                  <span class="help-inline" id="{{ field.html_name }}-help"></span>
                                </div>
                              </td>
                                </tr>
                            {% endfor %}
                          </table>
                      </form>
                      <!-- END COMPANY FORM -->
                    <!-- END MODAL BODY -->
                </div>
                <div class="modal-footer">
                    <a role="button" class="btn btn-default" data-dismiss="modal">Close</a>
                    <a role="button" class="btn btn-primary set-company-form-submit">Ok</a>
                </div>
            </div>
        </div>
    </div>
    <!-- END MODAL -->

 <!-- END COMPANIES INDEX CONTENT -->
{% endblock %}