supportportal/apps/support/contact/urls.py
from django.conf.urls import patterns, url
from apps.support.contact import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
)

supportportal/apps/support/tickets/urls.py
from django.conf.urls import patterns, url
from apps.support.tickets import views

urlpatterns = patterns('',
    # Views
    url(r'^index/$', views.index, name='index'),
    url(r'^detail/(?P<ticket_id>\d+)/$', views.detail, name='detail'),
    url(r'^admin/$', views.admin, name='admin'),
    # AJAX
    url(r'^list/$', views.get_tickets, name='gettickets'),
    url(r'^create/$', views.create_ticket, name='create_ticket'),
    url(r'^create/(?P<service_id>\d+)/$', views.create_ticket, name='create_ticket'),
    url(r'^posts/(?P<ticket_id>\d+)/$', views.get_posts, name='getposts'),
    url(r'^get/(?P<ticket_id>\d+)/$', views.get_ticket, name='getticket'),
    url(r'^set/(?P<ticket_id>\d+)/$', views.set_ticket, name='setticket'),
    url(r'^reply/(?P<ticket_id>\d+)/$', views.create_post, name='setpost'),
    url(r'^contacts/(?P<ticket_id>\d+)/$', views.set_contacts, name='set_contacts'),
    url(r'^visibility/(?P<post_id>\d+)/$', views.toggle_visibility, name='togglevisibility'),
    url(r'^postrating/(?P<post_id>\d+)/$', views.set_post_rating, name='setpostrating'),
    url(r'^satisfaction/(?P<ticket_id>\d+)/$', views.set_satisfaction_rating, name='setsatisfaction'),
    url(r'^summary/$', views.get_summary, name='summary'),
    url(r'^getqueue/$', views.get_queue, name='getqueue'),
    url(r'^setqueue/$', views.set_queue, name='setqueue'),
    url(r'^delqueue/$', views.delete_queue, name='delqueue'),
    url(r'^getmacros/$', views.get_macros, name='getmacros'),
    url(r'^setmacro/$', views.set_macro, name='setmacro'),
    url(r'^delmacro/$', views.delete_macro, name='delmacro'),
)

supportportal/appsdir/support/urls.py
from django.conf.urls import patterns, url
from appsdir.support import views

urlpatterns = patterns('',
    url(r'^index/$', views.index, name='index'),
    url(r'^detail/(?P<ticket_id>\d+)/$', views.detail, name='detail'),
    url(r'^admin/$', views.admin, name='admin'),
    url(r'^new/$', views.new, name='new'),
)

supportportal/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from api import router

urlpatterns = patterns('',
    url('^activity/', include('actstream.urls')),
    url('^dashboard/', include('appsdir.dashboard.urls', namespace='dashboard')),
    url('^search/', include('appsdir.search.urls', namespace='search')),
    url('^support/', include('appsdir.support.urls', namespace='tickets')),
    url('^knowledgebase/', include('appsdir.knowledgebase.urls', namespace='knowledgebase')),
    url('^login/', 'django.contrib.auth.views.login', {'template_name': 'registration/login.html'}, name='login'),
    url('^logout/', 'django.contrib.auth.views.logout', {'next_page': '/login/'}),
    url('^accounts/contact/', include('appsdir.contacts.urls', namespace='contacts')),
    url('^accounts/company/', include('appsdir.companies.urls', namespace='companies')),
    url('^reports/', include('appsdir.reports.urls', namespace='reports')),
    url('^groups/', include('appsdir.groups.urls', namespace='groups')),
    url('^announcements/', include('appsdir.announcements.urls', namespace='announcements')),
    url('^api/', include(router.urls)),
    url('^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url('^$', 'django.contrib.auth.views.login', {'template_name': 'registration/login.html'}, name='login'),
)

if settings.DEBUG:
    urlpatterns += patterns('', ('^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

supportportal/apps/support/knowledgebase/models.py
from django.db import models
from django.conf import settings
from datetime import datetime
from django.forms.models import model_to_dict
from django.template import defaultfilters


class Category(models.Model):
    title = models.SlugField(max_length=64, null=False, blank=False, unique=True)

    def __unicode__(self):
        return '%s' % (self.title)


class Tag(models.Model):
    title = models.SlugField(max_length=64, null=False, blank=False, unique=True)

    def __unicode__(self):
        return '%s' % (self.title)


class Article(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, null=False, blank=False)
    title = models.CharField(max_length=128, blank=False, null=False)
    contents = models.TextField(blank=False, null=False)
    created = models.DateTimeField(editable=False)
    modified = models.DateTimeField()
    views = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(Category, blank=False, null=False)
    tags = models.ManyToManyField(Tag, blank=True, null=True)

    def __unicode__(self):
        return '%s' % (self.title)

    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
                self.created = datetime.today()
        self.modified = datetime.today()
        super(Article, self).save(*args, **kwargs)

    def dump_to_dict(self):
    	tags = []
    	for tag in self.tags.all():
    		tags.append({"id": tag.pk, "title": tag.title})

        return {
            "id": self.pk,
        	"author": self.author.get_full_name(),
        	"title": self.title,
        	"views": self.views,
        	"category": self.category.title,
            "category_id": self.category.pk,
        	"created": defaultfilters.date(self.created, "SHORT_DATETIME_FORMAT"),
        	"modified": defaultfilters.date(self.modified, "SHORT_DATETIME_FORMAT"),
        	"contents": self.contents,
        	"tags": tags
        }


def get_article_count(author_id=0, startdate=0, enddate=0):
    try:
        filters = dict()

        if author_id:
            filters.update({"author_id": author_id})

        if startdate and enddate:
            filters.update({"created__range": [startdate, enddate]})
        elif startdate:
            filters.update({"created__gt": startdate})

        return Article.objects.filter(**filters).count()
    except Exception as ex:
        return False


def increment_articles_views(article_id):
    """Increment Article views

        Increments view count on specified Article.

    Parameters
        article_id: int article id
    Returns
        bool result
    """
    try:
        Article.objects.filter(pk=article_id).update(views=models.F('views')+1)
        return True
    except Exception as ex:
        return False


def search(query):
    """Retrieves queryset of articles whose contents contains specified querystring.

    Parameters
    :param: str query - query string to search for

    Returns
    :queryset: Article
    """
    try:
        return Article.objects.filter(contents__icontains=query)
    except Exception as ex:
        return False

supportportal/apps/support/tickets/models.py
from django.db import models
from django.conf import settings
from datetime import datetime
from apps.companies.models import Service
from apps.contacts.models import Contact
from django.template import defaultfilters
from django.utils.timesince import timesince


class Queue(models.Model):
    EMAIL_TYPE_CHOICES = (
        ('pop3', 'POP3'),
        ('imap', 'IMAP4')
    )

    title = models.CharField(max_length=128, null=False, blank=False, unique=True)
    allow_email_submission = models.BooleanField(default=False, blank=True)
    email_address = models.EmailField(blank=True, null=True)
    email_type = models.CharField(max_length=5, blank=True, null=True, choices=EMAIL_TYPE_CHOICES)
    email_host = models.CharField(max_length=128, blank=True, null=True)
    email_port = models.IntegerField(blank=True, null=True)
    email_ssl = models.BooleanField(blank=True, default=False)
    email_username = models.CharField(max_length=128, blank=True, null=True)
    email_password = models.CharField(max_length=256, blank=True, null=True)
    email_fetch_interval = models.IntegerField(default=5, blank=True, null=True)
    email_last_checked = models.DateTimeField(blank=True, null=True, editable=False)

    def __unicode__(self):
        return "%s" % self.title

    def dump_to_dict(self, full=False):
        response = {
            'id': self.pk,
            'title': self.title,
            'allow_email_submission': self.allow_email_submission,
            'email_address': self.email_address if self.email_address else ""
        }

        if full:
            response.update({
                'email_address': self.email_address,
                'email_type': self.email_type,
                'email_host': self.email_host,
                'email_port': self.email_port,
                'email_ssl': self.email_ssl,
                'email_username': self.email_username,
                'email_fetch_interval': self.email_fetch_interval,
                'email_last_checked': defaultfilters.date(self.email_last_checked, "SHORT_DATETIME_FORMAT")
            })

        return response


class Ticket(models.Model):
    STATUS_OPEN = 1
    STATUS_CLOSED = 0

    STATUS_CHOICES = (
        (STATUS_CLOSED, 'Closed'),
        (STATUS_OPEN, 'Open'),
    )

    PRIORITY_LOW = 1
    PRIORITY_NORMAL = 2
    PRIORITY_URGENT = 3

    PRIORITY_CHOICES = (
        (PRIORITY_LOW, 'Low'),
        (PRIORITY_NORMAL, 'Normal'),
        (PRIORITY_URGENT, 'Urgent'),
    )

    SATISFACTION_VERY_DISSATISFIED = 1
    SATISFACTION_DISSATISFIED = 2
    SATISFACTION_NEUTRAL = 3
    SATISFACTION_SATISFIED = 4
    SATISFACTION_VERY_SATISFIED = 5

    SATISFACTION_CHOICES = (
        (SATISFACTION_VERY_DISSATISFIED, "Very Dissatisfied"),
        (SATISFACTION_DISSATISFIED, "Dissatisfied"),
        (SATISFACTION_NEUTRAL, "Neutral"),
        (SATISFACTION_SATISFIED, "Satisfied"),
        (SATISFACTION_VERY_SATISFIED, "Very Satisfied")
    )

    DIFFICULTY_SIMPLE = 1
    DIFFICULTY_EASY = 2
    DIFFICULTY_MEDIUM = 3
    DIFFICULTY_HARD = 4
    DIFFICULTY_ADVANCED = 5

    DIFFICULTY_CHOICES = (
        (DIFFICULTY_SIMPLE, "Simple"),
        (DIFFICULTY_EASY, "Easy"),
        (DIFFICULTY_MEDIUM, "Medium"),
        (DIFFICULTY_HARD, "Hard"),
        (DIFFICULTY_ADVANCED, "Advanced")
    )

    contacts = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, null=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="author", blank=False, null=False)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="owner", blank=True, null=True)
    priority = models.IntegerField(choices=PRIORITY_CHOICES, default=PRIORITY_NORMAL, blank=True)
    status = models.IntegerField(choices=STATUS_CHOICES, default=STATUS_OPEN, blank=True)
    flagged = models.BooleanField(default=True, blank=True)
    description = models.CharField(max_length=256, null=False, blank=False)
    date = models.DateTimeField(default=datetime.now, blank=True)
    service = models.ForeignKey(Service, blank=True, null=True)
    queue = models.ForeignKey(Queue, null=False, blank=False)
    due_date = models.DateTimeField(default=datetime.now, blank=True)
    staff_summary = models.TextField(blank=True, null=True)
    satisfaction_rating = models.IntegerField(choices=SATISFACTION_CHOICES, blank=True, default=0)
    difficulty_rating = models.IntegerField(choices=DIFFICULTY_CHOICES, blank=True, default=0)


    def __unicode__(self):
        return "%s" % self.description

    def dump_to_dict(self, full=False, admin=False):
        if self.priority == 1:
            priority = "Low"
        elif self.priority == 2:
            priority = "Normal"
        elif self.priority == 3:
            priority = "Urgent"

        response = {
            'id': self.pk,
            'description': self.description,
            'author': self.author.get_full_name(),
            'owner': self.owner.get_full_name() if self.owner else "Unassigned",
            'flagged': self.flagged,
            'queue': self.queue.title,
            'status': "Open" if self.status else "Closed",
            'priority': priority,
            'date': defaultfilters.date(self.date, "SHORT_DATETIME_FORMAT"),
            'due_date': defaultfilters.date(self.due_date, "SHORT_DATETIME_FORMAT"),
            'lastupdate': timesince(self.date),
        }

        if full:
            if admin:
                if self.difficulty_rating == 0:
                    difficulty_rating = "Not Rated"
                elif self.difficulty_rating == 1:
                    difficulty_rating = "Simple"
                elif self.difficulty_rating == 2:
                    difficulty_rating = "Easy"
                elif self.difficulty_rating == 3:
                    difficulty_rating = "Medium"
                elif self.difficulty_rating == 4:
                    difficulty_rating = "Hard"
                elif self.difficulty_rating == 5:
                    difficulty_rating == "Advanced"

                response.update({
                    'staff_summary': self.staff_summary if self.staff_summary else 0,
                    'difficulty_rating': difficulty_rating
                })

            response.update({
                'satisfaction_rating': self.satisfaction_rating if self.satisfaction_rating else 0,
                'cc_list': get_ticket_contacts_list(self.id, self.author.company_id),
                'service': self.service.name if self.service else "Other",
            })

        return response


class Post(models.Model):
    RATING_BAD = 1
    RATING_GOOD = 2

    RATING_CHOICES = (
        (RATING_BAD, 'Needs improvement'),
        (RATING_GOOD, 'Exemplary'),
    )

    def validate_file_extension(filename):
        import os
        ext = os.path.splitext(filename.name)[1]
        valid_extensions = ['.pdf','.jpg', '.png', '.txt']
        if not ext in valid_extensions:
            raise Exception('File extension not supported!')

    ticket = models.ForeignKey(Ticket, blank=False, null=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, blank=False, null=False)
    contents = models.TextField(blank=False, null=False)
    date = models.DateTimeField(auto_now_add=True, blank=True)
    visible = models.BooleanField(default=True, blank=True)
    attachment = models.FileField(upload_to="attachments/%Y/%m/%d", validators=[validate_file_extension], blank=True, null=True)
    rating = models.IntegerField(choices=RATING_CHOICES, blank=True, null=True)

    def __unicode__(self):
        return "%s" % self.contents

    def dump_to_dict(self):
        attachment = 0
        if self.attachment and hasattr(self.attachment, 'name'):
            attachment = {"url": self.attachment.url, "size": self.attachment.size, "name": self.attachment.name}

        return {
            "id": self.pk,
            "author": self.author.get_full_name(),
            "author_id": self.author.pk,
            "author_is_staff": self.author.is_staff,
            "contents": self.contents,
            "date": defaultfilters.date(self.date, "SHORT_DATETIME_FORMAT"),
            "attachment": attachment,
            'visible': self.visible,
            "rating": self.rating
        }


class Macro(models.Model):
    name = models.CharField(max_length=128, blank=False, null=False)
    body = models.TextField(blank=False, null=False)
    date = models.DateTimeField(default=datetime.now, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, blank=False, null=False)

    def __unicode__(self):
        return "%s" % self.name

    def dump_to_dict(self):
        return {
            'id': self.pk,
            'name': self.name,
            'body': self.body,
            'author': self.author.get_full_name()
        }






import logging
logger = logging.getLogger(__name__)


def get_ticket_count(owner_id=0, startdate=0, enddate=0, difficulty_rating=0, satisfaction_rating=0):
    try:
        filters = dict()

        if owner_id:
            filters.update({'owner_id': owner_id})

        if startdate and enddate:
            filters.update({'date__range': [startdate, enddate]})
        elif startdate:
            filters.update({'date__gt': startdate})
        elif enddate:
            filters.update({'date__lt': enddate})

        if difficulty_rating:
            filters.update({'difficulty_rating': difficulty_rating})

        if satisfaction_rating:
            filters.update({'satisfaction_rating': satisfaction_rating})

        return Ticket.objects.filter(**filters).count()
    except Exception as ex:
        logger.error("Failed to get_post_count: %s" % ex)
        return False

def get_post_count(author_id=0, rating=0, startdate=0, enddate=0):
    try:
        filters = dict()

        if author_id:
            filters.update({'author_id': author_id})

        if rating:
            filters.update({'rating': rating})

        if startdate and enddate:

supportportal/apps/support/knowledgebase/forms.py
from django.forms import ModelForm
from .models import Category, Article, Tag

class CategoryForm(ModelForm):
	class Meta:
		model = Category

class TagForm(ModelForm):
	class Meta:
		model = Tag

class ArticleForm(ModelForm):
	class Meta:
		model = Article
		exclude = ['author', 'modified']

supportportal/apps/support/contact/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


@login_required
def index(request):
    """Contact Base View

        Displays contact information.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        @login_required
            request.user.is_authenticated() must be True
    Parameters
        request: HttpRequest
    Returns
        HttpResponse (contact/index.html)
    """
    return render(request, 'contact/index.html')

supportportal/appsdir/support/templates/support/new.html
{% extends "base.html" %}

{% load staticfiles %}
{% load common_tags %}

{% block sitetitle %}| Support{% endblock %}
{% block heading %}Support <small>Trouble Tickets</small>{% endblock %}

{% block breadcrumbs %}
    <li><a>Support</a><i class="fa fa-circle"></i></li>
    <li><a href="{% url 'tickets:index' %}">Tickets</a><i class="fa fa-circle"></i></li>
    <li>Create Ticket</li>
{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css' %}" />
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js' %}"></script>
{% endblock %}

{% block inline_js %}
        {% if user.is_staff %}
            // Fetch Companies
            function getCompanies() {
                $.ajax({
                    url: "/api/companies/?format=json",
                    type: "GET",
                })
                .done(function(result) {
                    for(x in result.results) {
                        $("#id_company").append('<OPTION value="'+result.results[x].id+'">'+result.results[x].name+'</OPTION>');
                    }

                    getCompanyContacts($("#id_company").val());
                })
                .fail(function(jqXHR, textStatus, errorThrown) {
                    console.log("Failed to getCompanies(): " + textStatus);
                });
            }

            // Fetch Company's Contacts
            function getCompanyContacts(company_id) {
                $("#id_author").html("");

                $.ajax({
                    url: "/api/contacts/?company="+company_id+"&format=json",
                    type: "GET",
                })
                .done(function(result) {
                    for(x in result.results) {
                        $("#id_author").append('<OPTION value="'+result.results[x].id+'">'+result.results[x].first_name+' '+result.results[x].last_name+' ('+result.results[x].email+')</OPTION>');
                    }
                })
                .fail(function(jqXHR, textStatus, errorThrown) {
                    console.log("Failed to getCompanyContacts("+company_id+"): " + textStatus);
                });
            }
        {% endif %}

        function submitTicket() {
            var data = $("#create-ticket-form").serialize();

            $.ajax({
                url: "/api/support/tickets/",
                type: "POST",
                data: data,
            })
            .done(function(result) {
                submitPost(result.id);
            })
            .fail(function(jqXHR, textStatus, errorThrown) {
                console.log("Failed to submitTicket(): " + textStatus);
            });
        }

        function submitPost(ticket_id) {
            $("#post-form-ticket").val(ticket_id);

            {% if user.is_staff %}
                $("#post-form-author").val($("#create-ticket-form #id_author").val());
            {% else %}
                $("#post-form-author").val({{ user.id }});
            {% endif %}

            $.ajax({
                url: "/api/support/posts/",
                type: "POST",
                data: $("#create-post-form").serialize(),
            })
            .done(function(result) {
                window.location = "{% url 'tickets:detail' 0 %}".replace(0, ticket_id);
            })
            .fail(function(jqXHR, textStatus, errorThrown) {
                console.log("Failed to submitPost(): " + textStatus);
            });
        }
{% endblock %}

{% block jquery_document_ready %}
    {% if user.is_staff %}
        getCompanies();
        $('#id_company').on('change', function () {
            getCompanyContacts($(this).val());
        });
    {% else %}
        $("#id_contacts option").each(function(x,y) {
            if($(this).val()=={{ user.id }}) {
                $(this).prop('selected', true);
            }
        });
    {% endif %}

    $('#id_due_date').datetimepicker();

    $(document)
        .on('click', 'a.ticket-form-submit', function (e) {
            e.preventDefault();
            submitTicket();
        })
        .on('click', 'a.reset-form', function (e) {
            e.preventDefault();
            $("#create-ticket-form").trigger('reset');
            $("#create-post-form").trigger('reset');
        });
{% endblock %}

{% block content %}
    <!-- BEGIN TICKET PORTLET -->
    <div class="portlet light form-fit">
        <div class="portlet-title">
          <div class="caption">
            <i class="fa fa-cogs font-green-sharp"></i>
            <span class="caption-subject font-green-sharp bold uppercase">Create Ticket</span>
          </div>
        </div>
        <div class="portlet-body form">
            <div class="well" style="text-indent: 40px"><span>File attachments are allowed in the next screen.</span></div>

            {% if form_errors %}
                {{ form_errors }}
            {% endif %}

            <!-- BEGIN FORM-->
            <form role="form" id="create-ticket-form" class="form-horizontal form-bordered" enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                <table class="table table-hover" id="company-profile-form-table">
                    {% if user.is_staff %}
                    <tr class="form-group">
                        <td><label class="control-label">Company</label></td>
                        <td><select class="form-control" name="company" id="id_company" autocomplete="off"></select></td>
                    </tr>
                    {% else %}
                        <input type="hidden" name="author" id="id_author" value={{ user.id }} />
                    {% endif %}

                    {% for field in ticketform %}
                        <tr class="form-group">
                            <td><label class="control-label">{{ field.label_tag }}</label></td>
                            <td>
                                <div class="controls">
                                    {{ field|addcss:"form-control" }}
                                    <span id="{{ field.html_name }}-help" class="help-inline"></span>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
            </form>
            <form role="form" id="create-post-form" class="form form-vertical" enctype="multipart/form-data" method="POST">
                    <input type="hidden" name="ticket" id="post-form-ticket" value="0" />
                    <input type="hidden" name="author" id="post-form-author" value="0" />
                    <input type="hidden" name="visible" id="id_visible" value=true />
                    {% for field in postform %}
                        <tr class="form-group">
                            <td><label class="control-label">{{ field.label_tag }}</label></td>
                            <td>
                                <div class="controls">
                                    {% if field.html_name != "attachment" %}
                                        {{ field|addcss:"form-control" }}
                                    {% else %}
                                        {{ field }}
                                    {% endif %}
                                    <span id="{{ field.html_name }}-help" class="help-inline"></span>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}

                    <tr id="form-controls-container" class="form-actions">
                        <td>&nbsp;</td>
                        <td>
                            <a type="submit" class="btn btn-primary ticket-form-submit" role="button"><i class="fa fa-check"></i>&nbsp;Submit</a>
                            <a type="button" class="btn btn-danger reset-form" role="button"><i class="fa fa-refresh"></i>&nbsp;Reset</a>
                        </td>
                    </tr>
                </table>
            </form>
            <!-- END FORM-->
        </div>
    </div>
    <!-- END TICKET PORTLET -->
{% endblock %}