supportportal/apps/announcements/urls.py
from django.conf.urls import patterns, url
from apps.announcements import views

urlpatterns = patterns('',
    # AJAX
    url(r'^index/$', views.get_index, name='getall'),
    url(r'^detail/$', views.get_detail, name='get'),
    url(r'^set/$', views.set, name='setnews'),
    url(r'^del/$', views.delete, name='delnews'),
)

supportportal/appsdir/announcements/urls.py
from django.conf.urls import patterns, url
from appsdir.announcements import views


urlpatterns = patterns('',
    url(r'^(?P<announcement_id>\d+)/$', views.detail, name='detail'),
    url(r'^$', views.index, name='index'),
)

supportportal/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from api import router

urlpatterns = patterns('',
    url('^activity/', include('actstream.urls')),
    url('^dashboard/', include('appsdir.dashboard.urls', namespace='dashboard')),
    url('^search/', include('appsdir.search.urls', namespace='search')),
    url('^support/', include('appsdir.support.urls', namespace='tickets')),
    url('^knowledgebase/', include('appsdir.knowledgebase.urls', namespace='knowledgebase')),
    url('^login/', 'django.contrib.auth.views.login', {'template_name': 'registration/login.html'}, name='login'),
    url('^logout/', 'django.contrib.auth.views.logout', {'next_page': '/login/'}),
    url('^accounts/contact/', include('appsdir.contacts.urls', namespace='contacts')),
    url('^accounts/company/', include('appsdir.companies.urls', namespace='companies')),
    url('^reports/', include('appsdir.reports.urls', namespace='reports')),
    url('^groups/', include('appsdir.groups.urls', namespace='groups')),
    url('^announcements/', include('appsdir.announcements.urls', namespace='announcements')),
    url('^api/', include(router.urls)),
    url('^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url('^$', 'django.contrib.auth.views.login', {'template_name': 'registration/login.html'}, name='login'),
)

if settings.DEBUG:
    urlpatterns += patterns('', ('^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

supportportal/apps/announcements/models.py
from django.conf import settings
from django.db import models
from datetime import datetime
from django.template import defaultfilters

class Announcement(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, blank=False, null=False)
    timestamp = models.DateTimeField(default=datetime.now)
    title = models.CharField(max_length=256, blank=False, null=False)
    body = models.TextField(blank=False, null=False)
    public = models.BooleanField(default=False, blank=False)

    class Meta:
        ordering = ('-timestamp', )

    def dump_to_dict(self):
        return {
            'id': self.pk,
            'public': self.public,
            'author': self.author.get_full_name(),
            'timestamp': defaultfilters.date(self.timestamp, "SHORT_DATETIME_FORMAT"),
            'body': self.body,
            'title': self.title
        }

    def __unicode__(self):
        return "%s @ %s" % (self.author, self.timestamp)

supportportal/appsdir/announcements/models.py
from django.conf import settings
from django.db import models
from simple_history.models import HistoricalRecords


class Announcement(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="%(app_label)s_%(class)s_author", editable=False, null=True)
    title = models.CharField(max_length=64)
    body = models.TextField()
    public = models.BooleanField(default=False, blank=True)
    status = models.BooleanField(default=True, blank=True)
    history = HistoricalRecords()
    changed_by = models.ForeignKey(settings.AUTH_USER_MODEL, editable=False, null=True, related_name="%(app_label)s_%(class)s_changed_by")
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created', )

    def __unicode__(self):
        return "%s" % self.title

    def get_absolute_url(self):
        return "/announcements/%i/" % self.id

    @property
    def _history_user(self):
        return self.changed_by

supportportal/apps/announcements/forms.py
from django.forms import ModelForm
from .models import Announcement

class AnnouncementForm(ModelForm):
	class Meta:
		model = Announcement
		fields = ['title', 'body', 'public']

supportportal/appsdir/announcements/forms.py
from django.forms import ModelForm
from .models import Announcement


class AnnouncementForm(ModelForm):
	class Meta:
		model = Announcement
		fields = ['title', 'body', 'public']

supportportal/apps/announcements/views.py
# System
import logging
# Project
from apps.loggers.models import ActionLogger
from common.decorators import validated_request, validated_staff
from common.helpers import format_ajax_response
# App
from .models import Announcement
from .forms import AnnouncementForm


logger = logging.getLogger(__name__)


@validated_request(None)
def get_index(request):
    """Get News postings

        Retrieves the most recent news postings from the local database.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        @validated_request
            request.method must be POST
            request.is_ajax() must be True
            request.user.is_authenticated() must be True
    Paremeters
        request: HttpRequest
    Returns
        HttpResponse (JSON)
            success: int status result
            message: str response message
            *data:
                news:
                    title: str title of news posting
                    body: str contents of news posting
                    timestamp: str short formatted time of posting
                    author: str posting's author's name
    """
    try:
        if request.user.is_staff:
            qset = Announcement.objects.order_by('-timestamp')[:5]
        else:
            qset = Announcement.objects.filter(public=True).order_by('-timestamp')[:5]

        news = []
        for post in qset:
            news.append(post.dump_to_dict())

        return format_ajax_response(True, "News retrieved successfully.", {"news": news})
    except Exception as ex:
        logger.error("Failed to get_news: %s" % ex)
        return format_ajax_response(False, "There was a problem retrieving News postings.")

@validated_staff
@validated_request(None)
def get_detail(request):
    try:
        announcement = Announcement.objects.get(pk=int(request.POST['announcement_id']))
        return format_ajax_response(True, "Announcement retrieved successfully.", {'announcement': announcement.dump_to_dict()})
    except Exception as ex:
        logger.error("Failed to get: %s" % ex)
        return format_ajax_response(False, "There was a problem retrieving the announcement.")

@validated_staff
@validated_request(AnnouncementForm)
def set(request):
    """Set a News posting

        Creates a News posting in the local database.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        @validated_staff
            request.user.is_staff must be True
        @validated_request
            request.POST must validate against AnnouncementForm
            request.method must be POST
            request.is_ajax() must be True
            request.user.is_authenticated() must be True
    Paremeters
        request: HttpRequest
    Returns
        HttpResponse (JSON)
            success: int status result
            message: str response message
    """
    try:
        if "announcement_id" not in request.POST or not request.POST["announcement_id"]:
            # Create new
            post = Announcement.objects.create(title=request.form.cleaned_data["title"], body=request.form.cleaned_data["body"], author=request.user)
            ActionLogger().log(request.user, "created", "Announcement %s" % post)
            return format_ajax_response(True, "Announcement created successfully.")
        else:
            # Update existing
            post = Announcement.objects.get(pk=int(request.POST["announcement_id"]))
            post.title = request.form.cleaned_data["title"]
            post.body = request.form.cleaned_data["body"]
            post.author = request.user
            if "public" in request.POST and request.POST['public'] == "on":
                post.public= True
            else:
                post.public=False
            post.save()

            ActionLogger().log(request.user, "modified", "Announcement %s" % post)
            return format_ajax_response(True, "Announcement updated successfully.")
    except Exception as ex:
        logger.error("Failed to set: %s" % ex)
        return format_ajax_response(False, "There was a problem setting the specified announcement.")


@validated_staff
@validated_request(None)
def delete(request):
    """Delete News posting

        Deletes News posting(s) from the local database.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        @validated_staff
            request.user.is_staff must be True
        @validated_request
            request.POST must validate against AnnouncementForm
            request.method must be POST
            request.is_ajax() must be True
            request.user.is_authenticated() must be True
    Paremeters
        request: HttpRequest
    Returns
        HttpResponse (JSON)
            success: int status result
            message: str response message
    """
    try:
        posts = request.POST.getlist('announcement_id')
        Announcement.objects.filter(pk__in=posts).delete()
        ActionLogger().log(request.user, "deleted", "News Article(s) %s" % posts)
        return format_ajax_response(True, "News Article(s) deleted successfully.")
    except Exception as ex:
        logger.error("Failed to delete_news: %s" % ex)
        return format_ajax_response(False, "There was a problem deleting the specified article(s).")

supportportal/appsdir/announcements/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import get_object_or_404, render
from .models import Announcement
from .forms import AnnouncementForm


@login_required
def detail(request, announcement_id):
    """Company Detail View

        Retrieve Company details as specified by company.pk.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        @login_required
            request.user.is_authenticated() must be True
    Parameters
        request: HttpRequest
        announcement_id: int company id
    Returns
        HttpResponse (announcements/detail.html)
            company_detail: queryset Company of specified announcement_id
            company_form: form CompanyForm
            contact_form: form ContactCreationForm
    """
    return render(request, 'announcements/detail.html', {'announcement_id': announcement_id})

@staff_member_required
def index(request):
    """Announcement Index View

        Retrieves listing of Announcements.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        @staff_member_required
            request.user.is_staff() must be True
    Parameters
        request: HttpRequest
    Returns
        HttpResponse (announcements/index.html)
            announcementform: form AnnouncementForm
    """
    return render(request, 'announcements/index.html', {'announcementform':  AnnouncementForm()})

supportportal/appsdir/announcements/templates/announcements/detail.html
{% extends "base.html" %}

{% load staticfiles %}
{% load common_tags %}

{% block sitetitle %}| Announcements{% endblock %}
{% block heading %}Announcements <small>Detail</small>{% endblock %}

{% block breadcrumbs %}
	<li><a{% if user.is_staff %} href="{% url 'announcements:index' %}"{% endif %}>Announcements</a><i class="fa fa-circle"></i></li>
	<li class="announcement-title"></li>
{% endblock %}

{% block inline_js %}
    // Fetch Annoucement Detail
    function getAnnouncement() {
      $.ajax({
        url: "/api/announcements/"+{{ announcement_id }}+"/?format=json",
        type: "GET",
      })
      .done(function(result) {
        $(".announcement-title").html(result["title"]);
        $("#announcement-body").html(result["body"]);
        $("#announcement-byline").html('<a href="'+"{% url 'contacts:detail' 0 %}".replace(0, result["author"])+'">'+result["author_name"]+"</a> @ "+result["created"]);
      })
      .fail(function(jqXHR, textStatus, errorThrown) {
        console.log("Failed to getAnnouncement(" + {{ announcement_id }} + "): " + textStatus);
        $('.modal-alert').fadeIn();
        $('.modal-alert').html('<div class="alert alert-danger">There was an error fetching the Announcement details.</div>');
      });
    }
{% endblock %}

{% block jquery_document_ready %}
	getAnnouncement();
{% endblock %}

{% block content %}
      <div class="portlet light bordered">
        <div class="portlet-title">
          <div class="caption col-md-6">
            <i class="icon-pin font-green-sharp"></i><span class="caption-subject bold font-green-sharp uppercase announcement-title"></span>
          </div>
          <div class="col-md-6 text-right"><small id="announcement-byline"></small></div>
        </div>
        <div class="portlet-body">
          <div id="announcement-body" style="margin: 20px"></div>
        </div>
      </div>
{% endblock %}

supportportal/appsdir/announcements/templates/announcements/index.html
{% extends "base.html" %}

{% load staticfiles %}
{% load common_tags %}

{% block sitetitle %}| Announcements{% endblock %}
{% block heading %}Administration <small>Announcements</small>{% endblock %}

{% block breadcrumbs %}
    <li>Announcements</a></li>
{% endblock %}

{% block css %}
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link rel="stylesheet" href="{% static 'plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css' %}" />
    <!-- END PAGE LEVEL STYLES -->
{% endblock %}

{% block js %}
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script type="text/javascript" src="{% static 'plugins/datatables/media/js/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js' %}"></script>
    <!-- END PAGE LEVEL PLUGINS -->
{% endblock %}

{% block inline_js %}
    // Create or Update Announcement
    function setAnnouncement(announcement_id, data) {
        var http_verb = "POST";
        var http_url = "/api/announcements/";

        if(announcement_id > 0) {
            http_verb = "PATCH";
            http_url += announcement_id + "/";
        }

        if(data["public"] == "on") {
          data["public"] = true;
        }

        $.ajax({
            url: http_url,
            type: http_verb,
            data: data,
        })
        .done(function(result) {
            console.log("Announcement " + announcement_id + " updated successfuly.");
            $('.modal-alert').fadeIn();
            $('.modal-alert').html('<div class="alert alert-success">Announcement updated successfully.</div>');
            setTimeout("$('.modal.in').modal('hide')",500);
        })
        .fail(function(jqXHR, textStatus, errorThrown) {
            console.log("Failed to update announcement:" + announcement_id + " " + textStatus);
            $('.modal-alert').fadeIn();
            $('.modal-alert').html('<div class="alert alert-danger">Failed to update announcement.</div>');

            $.each(jqXHR["responseJSON"], function(key, value) {
                $("#set-announcement-form #id_"+key).closest('tr').addClass("has-error");
                $("#set-announcement-form #"+key+"-help").html(value);
            });
        });
    }

    // Fetch Annoucement Detail
    function getAnnouncement(announcement_id) {
      if(announcement_id !== parseInt(announcement_id, 10)) {
        console.log("Invalid Announcement ID passed to getAnnouncement().");
        return False;
      }

      $.ajax({
        url: "/api/announcements/"+announcement_id+"/?format=json",
        type: "GET",
      })
      .done(function(result) {
        $("#set-announcement-form #announcement_id").val(announcement_id);
        $("#set-announcement-form #id_public").prop('checked', result["public"]);
        $.each(result, function(x,y) {
          $("#set-announcement-form #id_"+x).val(y);
        });
      })
      .fail(function(jqXHR, textStatus, errorThrown) {
        console.log("Failed to getAnnouncement(" + announcement_id + "): " + textStatus);
        $('.modal-alert').fadeIn();
        $('.modal-alert').html('<div class="alert alert-danger">There was an error fetching the Announcement details.</div>');
      });
    }

    // Fetch Announcements Index
    function getAnnouncements() {
        $("#announcements-table").dataTable().fnDestroy();
        $("#announcements-table-tbody").html("");

        $.ajax({
            url: "/api/announcements/?format=json",
            type: "GET",
        })
        .done(function(result) {
          for(x in result.results) {
              $("#announcements-table-tbody").append(' \
                  <tr data-id="'+result.results[x].id+'" data-public="'+result.results[x].public+'" data-status="'+result.results[x].status+'"> \
                      <td><input type="checkbox" value="1" class="checkboxes"></td> \
                      <td><a href="'+"{% url 'announcements:detail' 0 %}".replace('0', result.results[x].id)+'">'+result.results[x].title+'</a></td> \
                      <td><a href="'+"{% url 'contacts:detail' 0 %}".replace('0', result.results[x].author)+'">'+result.results[x].author_name+'</a></td> \
                      <td>'+result.results[x].created+'</td> \
                      <td>'+result.results[x].public+'</td> \
                      <td>'+result.results[x].status+'</td> \
                  </tr>'
              );
          }

          initAnnouncementsTable();
        })
        .fail(function(jqXHR, textStatus, errorThrown) {
            console.log("Failed to getAnnouncements(): " + textStatus);
            $("#announcements-table-tbody").html('<tr class="has-error"><td colspan=6><em>There was an error fetching the announcements index.</em></td></tr>');
        });
    }

    var initAnnouncementsTable = function () {

        var table = $('#announcements-table');

        table.dataTable({

            // Internationalisation. For more info refer to http://datatables.net/manual/i18n
            "language": {
                "aria": {
                    "sortAscending": ": activate to sort column ascending",
                    "sortDescending": ": activate to sort column descending"
                },
                "emptyTable": "No data available in table",
                "info": "Showing _START_ to _END_ of _TOTAL_ entries",
                "infoEmpty": "No entries found",
                "infoFiltered": "(filtered1 from _MAX_ total entries)",
                "lengthMenu": "Show _MENU_ entries",
                "search": "Search:",
                "zeroRecords": "No matching records found"
            },

            "bDestroy": true,
            "bStateSave": true, // save datatable state(pagination, sort, etc) in cookie.

            "lengthMenu": [
                [10, 20, -1],
                [10, 20, "All"] // change per page values here
            ],
            // set the initial value
            "pageLength": 10,
            "language": {
                "lengthMenu": " _MENU_ records",
                "paging": {
                    "previous": "Prev",
                    "next": "Next"
                }
            },
            "columnDefs": [{  // set default column settings
                'orderable': false,
                'targets': [0]
            }, {
                "searchable": false,
                "targets": [0]
            }],
            "order": [
                [1, "desc"]
            ] // set first column as a default sort by asc
        });
    }
{% endblock %}

{% block jquery_document_ready %}
    getAnnouncements();

    $("#checkall").on('click', function(){
        if(this.checked) {
            $('.checkboxes').each(function() {
              this.checked = true;
            });
        }else{
            $('.checkboxes').each(function() {
              this.checked = false;
            });
        }
    });

    $(document)
        .on('click', 'a.show-set-announcement-modal', function (e) {
            e.preventDefault();
            resetModalForm("set-announcement", "announcement_id");
        })
        .on('click', 'a.edit-announcement', function (e) {
            e.preventDefault();
            if($("#announcements-table-tbody input[type=checkbox]:checked").length == 1) {
              var announcement_id = $("#announcements-table-tbody input[type=checkbox]:checked").closest('tr').data('id');
              if(announcement_id) {
                resetModalForm("set-announcement", "announcement_id");
                getAnnouncement(announcement_id);
              }
            }
        })
        .on('click', 'a.toggle-status', function (e) {
            e.preventDefault();
            $("#announcements-table-tbody input[type=checkbox]:checked").each(function() {
              setAnnouncement($(this).closest('tr').data('id'), {"status": !$(this).closest('tr').data('status')});
            });

            setTimeout("getAnnouncements()",500);
        })
        .on('click', 'a.toggle-visibility', function (e) {
            e.preventDefault();
            $("#announcements-table-tbody input[type=checkbox]:checked").each(function() {
              setAnnouncement($(this).closest('tr').data('id'), {"public": !$(this).closest('tr').data('public')});
            });

            setTimeout("getAnnouncements()",500);
        })
        .on('click', 'a.set-announcement-form-submit', function (e) {
            e.preventDefault();
            if($("#set-announcement-form #id_public").val()=="on") {
              $("#set-announcement-form #id_public").val(true);
            }
            setAnnouncement($("#set-announcement-form #announcement_id").val(), $("#set-announcement-form").serialize());
            getAnnouncements();
        });
{% endblock %}

{% block content %}
    <!-- BEGIN ANNOUNCEMENTS INDEX PORTLET -->
    <div class="portlet light">
        <div class="portlet-title">
          <div class="caption">
            <i class="fa fa-cogs font-green-sharp"></i>
            <span class="caption-subject font-green-sharp bold uppercase">Announcements</span>
          </div>
          <div class="actions btn-set">
            <a class="btn green-haze btn-circle show-set-announcement-modal" href="javascript:;"><i class="fa fa-check"></i> Add</a>
            <div class="btn-group">
              <a data-toggle="dropdown" href="javascript:;" class="btn yellow btn-circle" aria-expanded="false">
              <i class="fa fa-check-circle"></i> Edit <i class="fa fa-angle-down"></i>
              </a>
              <ul class="dropdown-menu pull-right">
                <li><a href="javascript:;" class="edit-announcement"> Modify Announcement </a></li>
                <li><a href="javascript:;" class="toggle-status"> Toggle Status </a></li>
                <li><a href="javascript:;" class="toggle-visibility"> Toggle Visibility </a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="portlet-body">
          <table id="announcements-table" class="table table-striped table-bordered table-hover dataTable no-footer" role="grid">
            <thead>
              <tr role="row">
                <th class="table-checkbox sorting_disabled" rowspan="1" colspan="1" style="width: 24px;" aria-label="">
                  <input type="checkbox" data-set="#announcements-table .checkboxes" id="checkall" class="checkboxes">
                </th>
                <th class="sorting_desc" tabindex="0" aria-controls="announcements-table" rowspan="1" colspan="1" aria-sort="descending" aria-label="Name">Title</th>
                <th class="sorting" tabindex="0" aria-controls="announcements-table" rowspan="1" colspan="1" aria-label="Email">Author</th>
                <th class="sorting" tabindex="0" aria-controls="announcements-table" rowspan="1" colspan="1" aria-label="Company">Created</th>
                <th class="sorting" tabindex="0" aria-controls="announcements-table" rowspan="1" colspan="1" aria-label="Public">Public</th>
                <th class="sorting" tabindex="0" aria-controls="announcements-table" rowspan="1" colspan="1" aria-label="Status">Status</th>
              </tr>
            </thead>
            <tbody id="announcements-table-tbody"></tbody>
          </table>
        </div>
    </div>
    <!-- END ANNOUNCEMENTS INDEX PORTLET -->

    <!-- BEGIN SET ANNOUNCEMENT MODAL -->
    <div id="set-announcement-modal" class="modal fade in" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3>Add Announcement</h3>
                </div>
                <div class="modal-body">
                    <!-- BEGIN MODAL BODY -->
                    <div class="modal-alert"></div>
                      <!-- BEGIN ANNOUNCEMENT FORM -->
                      <form class="form form-vertical" role="form" id="set-announcement-form">
                        <input type="hidden" name="announcement_id" id="announcement_id" value="0" />
                        <table class="table table-hover" id="set-announcement-form-table">
                          {% for field in announcementform %}
                            <tr class="form-group">
                              <td><label class="control-label">{{ field.label_tag }}</label></td>
                              <td>
                                <div class="controls{% if field.errors %} error{% endif %}">
                                  {{ field|addcss:"form-control" }}
                                  <span class="help-inline" id="{{ field.html_name }}-help"></span>
                                </div>
                              </td>
                                </tr>
                            {% endfor %}
                          </table>
                      </form>
                      <!-- END ANNOUNCEMENT FORM -->
                    <!-- END MODAL BODY -->
                </div>
                <div class="modal-footer">
                    <a role="button" class="btn btn-default" data-dismiss="modal">Close</a>
                    <a role="button" class="btn btn-primary set-announcement-form-submit">Ok</a>
                </div>
            </div>
        </div>
    </div>
    <!-- END SET ANNOUNCEMENT MODAL -->
{% endblock %}