supportportal/apps/support/knowledgebase/urls.py
from django.conf.urls import patterns, url
from apps.support.knowledgebase import views

urlpatterns = patterns('',
    # Views
    url(r'^index/$', views.index, name='index'),
    url(r'^index/(?P<category_id>\d+)/$', views.index, name='index'),
    url(r'^index/(?P<category_id>\d+)/(?P<tag_id>\d+)/$', views.index, name='index'),
    url(r'^admin/$', views.admin, name='admin'),
    url(r'^admin/(?P<article_id>\d+)/$$', views.admin, name='admin'),
    url(r'^detail/(?P<article_id>\d+)/$', views.detail, name='detail'),
    # AJAX
    url(r'^getfeatured/$', views.get_featured_articles, name='getfeatured'),
    url(r'^getarticles/$', views.get_articles, name='getarticles'),
    url(r'^getarticle/(?P<article_id>\d+)/$', views.get_article, name='getarticle'),
    url(r'^setarticle/$', views.set_article, name='setarticle'),
    url(r'^delarticle/$', views.delete_article, name='delarticle'),
    url(r'^settag/$', views.set_tag, name='settag'),
    url(r'^gettags/$', views.get_tags, name='gettags'),
    url(r'^deltag/$', views.delete_tag, name='deltag'),
    url(r'^delcategory/$', views.delete_category, name='delcategory'),
    url(r'^setcategory/$', views.set_category, name='setcategory'),
    url(r'^getcategories/$', views.get_categories, name='getcategories'),
)

supportportal/appsdir/knowledgebase/urls.py
from django.conf.urls import patterns, url
from appsdir.knowledgebase import views

urlpatterns = patterns('',
    # Views
    url(r'^index/$', views.index, name='index'),
    url(r'^index/(?P<category_id>\d+)/$', views.index, name='index'),
    url(r'^index/(?P<category_id>\d+)/(?P<tag_id>\d+)/$', views.index, name='index'),
    url(r'^admin/$', views.admin, name='admin'),
    url(r'^admin/(?P<article_id>\d+)/$$', views.admin, name='admin'),
    url(r'^detail/(?P<article_id>\d+)/$', views.detail, name='detail'),
)

supportportal/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from api import router

urlpatterns = patterns('',
    url('^activity/', include('actstream.urls')),
    url('^dashboard/', include('appsdir.dashboard.urls', namespace='dashboard')),
    url('^search/', include('appsdir.search.urls', namespace='search')),
    url('^support/', include('appsdir.support.urls', namespace='tickets')),
    url('^knowledgebase/', include('appsdir.knowledgebase.urls', namespace='knowledgebase')),
    url('^login/', 'django.contrib.auth.views.login', {'template_name': 'registration/login.html'}, name='login'),
    url('^logout/', 'django.contrib.auth.views.logout', {'next_page': '/login/'}),
    url('^accounts/contact/', include('appsdir.contacts.urls', namespace='contacts')),
    url('^accounts/company/', include('appsdir.companies.urls', namespace='companies')),
    url('^reports/', include('appsdir.reports.urls', namespace='reports')),
    url('^groups/', include('appsdir.groups.urls', namespace='groups')),
    url('^announcements/', include('appsdir.announcements.urls', namespace='announcements')),
    url('^api/', include(router.urls)),
    url('^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url('^$', 'django.contrib.auth.views.login', {'template_name': 'registration/login.html'}, name='login'),
)

if settings.DEBUG:
    urlpatterns += patterns('', ('^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

supportportal/apps/support/knowledgebase/forms.py
from django.forms import ModelForm
from .models import Category, Article, Tag

class CategoryForm(ModelForm):
	class Meta:
		model = Category

class TagForm(ModelForm):
	class Meta:
		model = Tag

class ArticleForm(ModelForm):
	class Meta:
		model = Article
		exclude = ['author', 'modified']

supportportal/appsdir/knowledgebase/forms.py
from django.forms import ModelForm
from .models import Category, Article, Tag

class CategoryForm(ModelForm):
	class Meta:
		model = Category
		exclude = ['changed_by']

class TagForm(ModelForm):
	class Meta:
		model = Tag
		exclude = ['changed_by']

class ArticleForm(ModelForm):
	class Meta:
		model = Article
		exclude = ['author', 'modified', 'changed_by']

supportportal/apps/support/knowledgebase/views.py
# System
import logging
from django.shortcuts import render, get_object_or_404
# Project
from apps.loggers.models import ActionLogger
from common.decorators import validated_request, validated_staff
from common.helpers import format_ajax_response
# App
from .models import Article, Tag, Category, increment_articles_views
from .forms import CategoryForm, TagForm, ArticleForm


logger = logging.getLogger(__name__)


def index(request, category_id=0, tag_id=0):
    """Knowledgebase Index View

        Lists categories and popular/recently modified articles.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        None
    Parameters
        request: HttpRequest
        *category_id: int category id
        *tag_id: int tag id
    Returns
        HttpReponse (knowledgebase/index.html)
    """
    response = {}

    if int(category_id):
        category = get_object_or_404(Category, pk=category_id)
        response.update({
            'category_id': category_id,
            'category': category.title
        })
    elif int(tag_id):
        tag = get_object_or_404(Tag, pk=tag_id)
        response.update({
            'tag_id': tag_id,
            'tag': tag.title
        })

    return render(request, 'knowledgebase/index.html', response)


def detail(request, article_id):
    """Knowledgebase Detail View

        Retrieves specified article's details.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        None
    Parameters
        request: HttpRequest
        article_id: int article id
    Returns
        HttpResponse (knowledgebase/detail.html)
            article_id: int article id
    """
    return render(request, 'knowledgebase/detail.html', {'article_id': article_id})


@validated_staff
def admin(request):
    """Knowledgebase Admin View

        Lists categories and popular/recently modified articles.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        None
    Parameters
        request: HttpRequest
    Returns
        HttpReponse (knowledgebase/admin.html)
            articleForm: modelform ArticleForm
            categoryform: modelform CategoryForm
            tagform: modelform TagForm
    """
    response = {
        'articleform': ArticleForm(),
        'categoryform': CategoryForm(),
        'tagform': TagForm()
    }

    return render(request, 'knowledgebase/admin.html', response)


@validated_request(None)
def get_articles(request):
    """Get Articles

        Lists articles under optional category/tag.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        @validated_request
            request.method must be POST
            request.is_ajax() must be True
            request.user.is_authenticated() must be True
    Parameters
        request: HttpRequest
            *category_id: int category id
            *tag_id: int tag id
    Returns
        HttpResponse (JSON)
            success: int status result
            message: str response message
            *data:
                articles:
    """
    try:
        if 'category_id' in request.POST and int(request.POST['category_id']):
            queryset = Article.objects.filter(category_id=int(request.POST['category_id']))
        elif 'tag_id' in request.POST and int(request.POST['tag_id']):
            queryset = Article.objects.filter(tags__pk=request.POST['tag_id'])
        else:
            queryset = Article.objects.all()

        articles = []
        for article in queryset:
            articles.append(article.dump_to_dict())

        return format_ajax_response(True, "Knowledgebase articles listing retrieving successfully.", {"articles": articles})
    except Exception as ex:
        logger.error("Failed to get_articles: %s" % ex)
        return format_ajax_response(False, "There was an error retrieving knowledgebase articles listing.")


@validated_request(None)
def get_featured_articles(request):
    """Get Featured Articles

        Lists most popular and newest articles.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        @validated_request
            request.method must be POST
            request.is_ajax() must be True
            request.user.is_authenticated() must be True
    Parameters
        request: HttpRequest
        *count: int featured articles length
    Returns
        HttpResponse (JSON)
            success: int status result
            message: str response message
            *data:
                newest: dict of newest article(s)
                popular: dict of most viewed article(s)
    """
    try:
        count = 1
        if 'count' in request.POST and int(request.POST['count']):
            count = int(request.POST['count'])

        newest_list = []
        for article in Article.objects.order_by('-modified')[:count]:
            newest_list.append(article.dump_to_dict())

        popular_list = []
        for article in Article.objects.order_by('-views')[:count]:
            popular_list.append(article.dump_to_dict())

        return format_ajax_response(True, "Featured articles retrieved successfully.", {'newest': newest_list,'popular': popular_list})
    except Exception as ex:
        logger.error("Failed to get_featured_articles: %s" % ex)
        return format_ajax_response(False, "There was an error retrieving the featured articles.")


@validated_request(None)
def get_article(request, article_id):
    """Get Article

        Retrieves specified Article.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        @validated_request
            request.method must be POST
            request.is_ajax() must be True
            request.user.is_authenticated() must be True
    Parameters
        request: HttpRequest
        article_id: int article id
    Returns
        HttpResponse (JSON)
            success: int status result
            message: str response message
            *data:
                article:
                    id: int article id
                    author: str article's author name
                    title: str article title
                    views: int article view count
                    category: str article's category title
                    created: str article creation date
                    modified: str article last modified date
                    contents: str article contents
                    tags: dict (id,title) of article tags
    """
    try:
        article = Article.objects.get(pk=article_id)
        increment_articles_views(article_id)
        return format_ajax_response(True, "Knowledgebase article retrieved successfully.", {"article": article.dump_to_dict()})
    except Exception as ex:
        logger.error("Failed to get_article: %s" % ex)
        return format_ajax_response(False, "There was an error retrieving the knowledgebase article.")


@validated_staff
@validated_request(ArticleForm)
def set_article(request):
    """Set Article

        Creates new or updates existing Article.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        @validated_staff
            request.user.is_staff must be True
        @validated_request
            request.POST must validate against ArticleForm
            request.method must be POST
            request.is_ajax() must be True
            request.user.is_authenticated() must be True
    Parameters
        request: HttpRequest
            contents: str article contents
            title: str article title
            category: int category id
            *tags: int[] tag id's
            *article_id: int article id
    Returns
        HttpResponse (JSON)
            success: int status result
            message: str response message
    """
    try:
        # Update existing Article if article_id exists, else create new Article
        if "article_id" not in request.POST or not int(request.POST["article_id"]):
            # Create new Article
            article = Article.objects.create(category=request.form.cleaned_data["category"], contents=request.form.cleaned_data["contents"], title=request.form.cleaned_data["title"], author=request.user)

            tags = request.POST.getlist('tags', 0)
            if tags:
                article.tags.add(*tags)
                article.save()

            ActionLogger().log(request.user, "created", "Knowledgebase Article %s" % article)
            return format_ajax_response(True, "Knowledgebase article created successfully.", {"article_id": article.pk})
        else:
            # Update existing category
            article = Article.objects.get(pk=int(request.POST["article_id"]))
            article.views = request.form.cleaned_data["views"]
            article.title = request.form.cleaned_data["title"]
            article.contents = request.form.cleaned_data["contents"]
            article.category = request.form.cleaned_data["category"]

            article.tags.clear()
            tags = request.POST.getlist('tags', 0)
            if tags:
                article.tags.add(*tags)
            article.save()

            ActionLogger().log(request.user, "modified", "Knowledgebase Article %s" % article)
            return format_ajax_response(True, "Knowledgebase article updated successfully.", {"article_id": article.pk})
    except Exception as ex:
        logger.error("Failed to set_article: %s" % ex)
        return format_ajax_response(False, "There was an error setting the knowledgebase article.")


@validated_staff
@validated_request(None)
def delete_article(request):
    """Delete Article

        Deletes the specified Article.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        @validated_staff
            request.user.is_staff must be True
        @validated_request
            request.method must be POST
            request.is_ajax() must be True
            request.user.is_authenticated() must be True
    Parameters

supportportal/appsdir/knowledgebase/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.admin.views.decorators import staff_member_required
from .models import Article, Tag, Category
from .forms import CategoryForm, TagForm, ArticleForm


def index(request, category_id=0, tag_id=0):
    """Knowledgebase Index View

        Lists categories and popular/recently modified articles.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        None
    Parameters
        request: HttpRequest
        *category_id: int category id
        *tag_id: int tag id
    Returns
        HttpReponse (knowledgebase/index.html)
    """
    response = {}

    if int(category_id):
        category = get_object_or_404(Category, pk=category_id)
        response.update({
            'category_id': category_id,
            'category': category.title
        })
    elif int(tag_id):
        tag = get_object_or_404(Tag, pk=tag_id)
        response.update({
            'tag_id': tag_id,
            'tag': tag.title
        })

    return render(request, 'knowledgebase/index.html', response)


def detail(request, article_id):
    """Knowledgebase Detail View

        Retrieves specified article's details.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        None
    Parameters
        request: HttpRequest
        article_id: int article id
    Returns
        HttpResponse (knowledgebase/detail.html)
            article_id: int article id
    """
    return render(request, 'knowledgebase/detail.html', {'article_id': article_id})


@staff_member_required
def admin(request):
    """Knowledgebase Admin View

        Lists categories and popular/recently modified articles.

    Middleware
        See SETTINGS for active Middleware.
    Decorators
        staff_member_required
    Parameters
        request: HttpRequest
    Returns
        HttpReponse (knowledgebase/admin.html)
            articleform: modelform ArticleForm
            categoryform: modelform CategoryForm
            tagform: modelform TagForm
    """
    response = {
        'articleform': ArticleForm(),
        'categoryform': CategoryForm(),
        'tagform': TagForm()
    }

    return render(request, 'knowledgebase/admin.html', response)

supportportal/apps/support/knowledgebase/templates/knowledgebase/detail.html
{% extends "base.html" %}

{% block sitetitle %}| Support{% endblock %}
{% block heading %}Support <small>Knowledgebase</small>{% endblock %}

{% block breadcrumbs %}
	<li><a>Support</a></li>
	<li><a href="{% url 'knowledgebase:index' %}">Knowledgebase</a></li>
{% endblock %}

{% block js %}
	<script type="text/javascript">
		// Fetches Knowledgebase Articlediv
		function getArticle() {
			$("#article-stats").html("");

			function onSuccessCallback(result) {
				if(!jQuery.isEmptyObject(result) && result.hasOwnProperty('message') && result.hasOwnProperty('success') && result.hasOwnProperty('data')) {
					if(result.success == 1) {
						$("#article-title").html(result.data.article.title);
						$("#article-content").html(result.data.article.contents);
						$("#breadcrumbs").append('<li><a href="'+"{% url 'knowledgebase:index' 0 %}".replace(0, result.data.article.category_id)+'">'+result.data.article.category+'</a></li>')
						$("#breadcrumbs").append('<li>'+result.data.article.title+'</li>')

						var tags = "";
						if(result.data.article.tags.length) {
							for(x in result.data.article.tags) {
								tags += '<li><a href="'+"{% url 'knowledgebase:index' 0 9 %}".replace(9, result.data.article.tags[x].id)+'">'+result.data.article.tags[x].title+'</a></li>';
							}
						}

						$("#article-stats").append(' \
							<div class="row"> \
								<label class="col-md-4">Author</label> \
								<span class="col-md-8">'+result.data.article.author+'</span> \
							</div> \
							<div class="row"> \
								<label class="col-md-4">Category</label> \
								<span class="col-md-8"> \
									<a href="'+"{% url 'knowledgebase:index' 0 %}".replace(0, result.data.article.category_id)+'">'+result.data.article.category+'</a> \
								</span> \
							</div> \
							<div class="row"> \
								<label class="col-md-4">Created</label> \
								<span class="col-md-8">'+result.data.article.created+'</span> \
							</div> \
							<div class="row"> \
								<label class="col-md-4">Update</label> \
								<span class="col-md-8">'+result.data.article.modified+'</span> \
							</div> \
							<div class="row"> \
								<label class="col-md-4">Tags</label> \
								<span class="col-md-8"> \
									<ul class="list-inline">'+tags+'</ul> \
								</span> \
							</div>'
						);
					}
					else {
						$("#article-content").html('<div class="alert alert-danger">'+result.message+'</div>');
					}
				}
			}

			$.ajax({
                url: "{%url 'knowledgebase:getarticle' article_id %}",
                type: "POST",
                success: onSuccessCallback,
                error: defaultErrorCallback
            });
		}
	</script>
{% endblock %}

{% block jquery_document_ready %}
	getArticle();
{% endblock %}

{% block content %}
 <!-- BEGIN KNOWLEDGEBASE DETAIL CONTENT -->
    <!-- BEGIN CONTAINER HEAD -->
    <div class="row page-head">
        <div class="col-md-12">
        	<h3 id="article-title"></h3>
        </div>
    </div>
    <!-- END CONTAINER HEAD -->
    <!-- BEGIN CONTAINER BODY -->
	<div class="row">
		<!-- BEGIN LEFT COLUMN -->
		<div class="col-md-8">
			<div id="article-content"></div>
		</div>
		<!-- END LEFT COLUMN -->
		<!-- BEGIN RIGHT COLUMN -->
		<div class="col-md-4">
			<!-- BEGIN ARTICLE STATS -->
			<div id="article-stats" class="well row"></div>
			<!-- END ARTICLE STATS -->
		</div>
		<!-- END RIGHT COLUMN -->
	</div>
    <!-- END CONTAINER BODY -->
 <!-- END KNOWLEDGEBASE DETAIL CONTENT -->
{% endblock %}

supportportal/apps/support/knowledgebase/templates/knowledgebase/index.html
{% extends "base.html" %}

{% block sitetitle %}| Support{% endblock %}
{% block heading %}Support <small>Knowledgebase</small>{% endblock %}

{% block breadcrumbs %}
	<li><a>Support</a></li>
	{% if category_id %}
		<li><a href="{% url 'knowledgebase:index' %}">Knowledgebase</a></li>
		<li>{{ category }}</li>
	{% elif tag_id %}
		<li><a href="{% url 'knowledgebase:index' %}">Knowledgebase</a></li>
		<li>#{{ tag }}</li>
	{% else %}
		<li>Knowledgebase</li>
	{% endif %}
{% endblock %}

{% block js %}
	<script type="text/javascript">
		// Fetch Knowledgebase Articles
		function getArticles(category_id=0, tag_id=0) {
			$("#kb-articles").html("");

			function onSuccessCallback(result) {
				if(!jQuery.isEmptyObject(result) && result.hasOwnProperty('message') && result.hasOwnProperty('success') && result.hasOwnProperty('data')) {
					if(result.success == 1) {
						for(x in result.data.articles) {
							var articleContent = ' \
								<li class="list-group-item" data-id="'+result.data.articles[x].id+'"> \
									<a href="'+"{% url 'knowledgebase:detail' 0 %}".replace(0, result.data.articles[x].id)+'">'+result.data.articles[x].title+'</a> \
								</li>';

							{% if tag_id or category_id %}
								$("#kb-articles").append(articleContent);
							{% else %}
								$("#kb-categories li").each(function() {
									if($(this).data('id')==result.data.articles[x].category_id) {
										$("#kb-articles").append(articleContent);
									}
								})
							{% endif %}
						}
					}
				}
			}

			$.ajax({
                url: "{%url 'knowledgebase:getarticles' %}",
                data: {'category_id': category_id, 'tag_id': tag_id},
                type: "POST",
                success: onSuccessCallback,
                error: defaultErrorCallback
            });
		}

		// Fetch Knowledgebase Categories
		function getCategories() {
			function onSuccessCallback(result) {
				if(!jQuery.isEmptyObject(result) && result.hasOwnProperty('message') && result.hasOwnProperty('success') && result.hasOwnProperty('data')) {
					if(result.success == 1) {
						for(x in result.data.categories) {
							$("#kb-categories").append(' \
								<li class="list-group-item" data-id="'+result.data.categories[x].id+'"> \
									<a class="toggle-child">'+result.data.categories[x].title+'</a> \
								</li>'
							);
						}
					}
				}
			}

			$.ajax({
                url: "{%url 'knowledgebase:getcategories' %}",
                type: "POST",
                success: onSuccessCallback,
                error: defaultErrorCallback
            });
		}

		// Fetch Knowledgebase Featured Articles
		function getFeaturedArticles() {
			$("#kb-categories").html("");
			$("#popular-articles").html("");
			$("#newest-articles").html("");

			function onSuccessCallback(result) {
				if(!jQuery.isEmptyObject(result) && result.hasOwnProperty('message') && result.hasOwnProperty('success') && result.hasOwnProperty('data')) {
					if(result.success == 1) {
						for(x in result.data.newest) {
							$("#newest-articles").append(' \
								<li style="text-indent: 10px"> \
									<a href="'+"{%url 'knowledgebase:detail' 0 %}".replace(0, result.data.newest[x].id)+'"> \
										<em>'+result.data.newest[x].title+'</em> \
									</a> \
								</li>'
							);
						}

						for(x in result.data.popular) {
							$("#popular-articles").append(' \
								<li style="text-indent: 10px"> \
									<a href="'+"{%url 'knowledgebase:detail' 0 %}".replace(0, result.data.popular[x].id)+'"> \
										<em>'+result.data.popular[x].title+'</em> \
									</a> \
								</li>'
							);
						}
					}
					else {
						$("#kb-categories").html('<div class="alert alert-danger">'+result.message+'</div>');
					}
				}
			}

			$.ajax({
                url: "{%url 'knowledgebase:getfeatured' %}",
                data: {'count': 1},
                type: "POST",
                success: onSuccessCallback,
                error: defaultErrorCallback
            });
		}
	</script>
{% endblock %}

{% block jquery_document_ready %}
	getFeaturedArticles();

	{% if category_id %}
		getArticles({{ category_id }});
	{% elif tag_id %}
		getArticles(0, {{ tag_id }});
	{% else %}
		getCategories();

		$("#kb-categories")
	        .on('click', 'li', function (e) {
	        	if($(this).data('id')) {
		            e.preventDefault();
		            getArticles($(this).data('id'));
	            }
	        });
	{% endif %}
{% endblock %}

{% block content %}
 <!-- BEGIN KNOWLEDGEBASE INDEX CONTENT -->

	<!-- BEING KNOWLEDGEBASE CONTAINER -->
	     <!-- BEGIN CONTAINER HEAD -->
	    <div class="row page-head">
	        <div class="col-md-12">
	        	<h3>Knowledgebase
	        		{% if category_id %}
	        			:{{ category }}
	        		{% elif tag_id %}
	        			:#{{ tag }}
	        		{% endif %}
	        	</h3>
	        </div>
	    </div>
	    <!-- END CONTAINER HEAD -->
	    <!-- BEGIN CONTAINER BODY -->
		<div class="row">
			<!-- BEGIN LEFT COLUMN -->
			<div class="col-md-8 ">
				<div id="kb-categories" class="list-group list-unstyled" {% if category_id or tag_id %}style="display: none"{% endif %}></div>
				<div id="kb-articles" class="list-group list-unstyled"></div>
			</div>
			<!-- END LEFT COLUMN -->
			<!-- BEGIN RIGHT COLUMN -->
			<div class="col-md-4">
				<div class="control-group" id="featured-articles">
					<!-- BEGIN NEWEST ARTICLES -->
					<div class="panel panel-default">
					  <div class="panel-heading">Most Recent</div>
					  <div class="panel-body">
					  	<ul id="newest-articles" class="list-unstyled"></ul>
					  </div>
					</div>
					<!-- END NEWEST ARTICLES -->
					<!-- BEGIN POPULAR ARTICLES -->
					<div class="panel panel-default">
					  <div class="panel-heading">Most Popular</div>
					  <div class="panel-body">
					  	<ul id="popular-articles" class="list-unstyled"></ul>
					  </div>
					</div>
					<!-- END POPULAR ARTICLES -->
				</div>
			</div>
			<!-- END RIGHT COLUMN -->
		</div>
	    <!-- END CONTAINER BODY -->
    <!-- END KNOWLEDGEBASE CONTAINER -->

 <!-- END KNOWLEDGEBASE INDEX CONTENT -->
{% endblock %}